services:
  n8n:
    build:
      context: .
      dockerfile: n8n.Dockerfile
    container_name: gov-n8n
    user: root
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Sao_Paulo}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE:-false}
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:${N8N_PORT:-5678}/}
    volumes:
      - ./n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./workflows:/workflows
    depends_on:
      - scraper
    restart: unless-stopped

  scraper:
    build: ./scrapers
    container_name: gov-scrapers
    working_dir: /workspace
    environment:
      - HEADLESS=${HEADLESS:-true}
      - SCRAPE_CAL_QTY=${SCRAPE_CAL_QTY:-20}
      - SCRAPE_LACO_QTY=${SCRAPE_LACO_QTY:-20}
      - SCRAPE_SAM_QTY=${SCRAPE_SAM_QTY:-20}
    volumes:
      - .:/workspace
      - ./scrapers:/app
      - ./data:/data
      - ./tests:/tests
      - ./.coveragerc:/.coveragerc   # (so coverage omit rules work inside)
      - ./pytest.ini:/pytest.ini     # (so --cov-fail-under=70 etc. apply)
    command: tail -f /dev/null
    restart: unless-stopped
