services:
  n8n:
    build:
      context: .
      dockerfile: n8n.Dockerfile
    container_name: gov-n8n
    user: root                    # garante acesso ao /var/run/docker.sock
    ports:
      - "5897:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_SECURE_COOKIE=false
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_ENCRYPTION_KEY=icaro123@
    volumes:
      - ./n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    depends_on:
      - scraper
    restart: unless-stopped

  scraper:
    build: ./scrapers
    container_name: gov-scrapers
    working_dir: /app
    volumes:
      - ./scrapers:/app
      - ./data:/data
    command: tail -f /dev/null
    restart: unless-stopped



#services:
#  n8n:
#    image: n8nio/n8n
#    container_name: gov-n8n
#    ports:
#      - "5897:5678"
#    environment:
#      - GENERIC_TIMEZONE=America/Sao_Paulo
#      - N8N_BASIC_AUTH_ACTIVE=true
#      - N8N_BASIC_AUTH_USER=admin
#      - N8N_BASIC_AUTH_PASSWORD=admin
#      - N8N_SECURE_COOKIE=false
#    volumes:
#      - ./n8n_data:/home/node/.n8n
#    restart: unless-stopped

#  scraper:
#    build: ./scrapers
#    container_name: gov-lacobids-scraper
#    volumes:
#      - ./data:/app/data
#    command: tail -f /dev/null
#    restart: unless-stopped

#  scraper:
#    build: ./scrapers
#    image: icarolk/lacobids-scraper
#    container_name: gov-lacobids-scraper
#    volumes:
#      - ./scrapers:/app
#      - ./data:/app/data
#    command: python lacobids_scraper.py

#  app:
#    build: .
#    container_name: gov-scrapers
#    volumes:
#      - ./scrapers:/app/scrapers
#      - ./tests:/app/tests
#    working_dir: /app
#    command: tail -f /dev/null

